import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import Navbar from '@/components/Navbar'

import Provider from '@/components/Provider'
import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/route'
import SessionProviders from '@/components/SessionProviders'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession(authOptions)

  return (
    <html lang="en" className='light'>
      <Provider>
        <SessionProviders session={session} >

          <body className={cn('min-h-screen font-sans antialiased grains', inter.className)} >
            <Navbar />
            {children}
          </body>
        </SessionProviders>
      </Provider>
    </html>
  )
}
